// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: campaigns.public.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Campaigns_CreateCampaign_FullMethodName                   = "/campaigns.public.Campaigns/CreateCampaign"
	Campaigns_GetCampaignsList_FullMethodName                 = "/campaigns.public.Campaigns/GetCampaignsList"
	Campaigns_DepositTokensToSale_FullMethodName              = "/campaigns.public.Campaigns/DepositTokensToSale"
	Campaigns_JoinIdo_FullMethodName                          = "/campaigns.public.Campaigns/JoinIdo"
	Campaigns_Claim_FullMethodName                            = "/campaigns.public.Campaigns/Claim"
	Campaigns_Refund_FullMethodName                           = "/campaigns.public.Campaigns/Refund"
	Campaigns_WithdrawFunds_FullMethodName                    = "/campaigns.public.Campaigns/WithdrawFunds"
	Campaigns_CloseCampaign_FullMethodName                    = "/campaigns.public.Campaigns/CloseCampaign"
	Campaigns_WithdrawUnsoldTokens_FullMethodName             = "/campaigns.public.Campaigns/WithdrawUnsoldTokens"
	Campaigns_DeleteCampaign_FullMethodName                   = "/campaigns.public.Campaigns/DeleteCampaign"
	Campaigns_UpdateCampaignStatus_FullMethodName             = "/campaigns.public.Campaigns/UpdateCampaignStatus"
	Campaigns_CloseCampaignIfSoftCapNotReached_FullMethodName = "/campaigns.public.Campaigns/CloseCampaignIfSoftCapNotReached"
)

// CampaignsClient is the client API for Campaigns service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignsClient interface {
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error)
	GetCampaignsList(ctx context.Context, in *GetCampaignsListRequest, opts ...grpc.CallOption) (*GetCampaignsListResponse, error)
	DepositTokensToSale(ctx context.Context, in *DepositTokensToSaleRequest, opts ...grpc.CallOption) (*DepositTokensToSaleResponse, error)
	JoinIdo(ctx context.Context, in *JoinIdoRequest, opts ...grpc.CallOption) (*JoinIdoResponse, error)
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
	WithdrawFunds(ctx context.Context, in *WithdrawFundsRequest, opts ...grpc.CallOption) (*WithdrawFundsResponse, error)
	CloseCampaign(ctx context.Context, in *CloseCampaignRequest, opts ...grpc.CallOption) (*CloseCampaignResponse, error)
	WithdrawUnsoldTokens(ctx context.Context, in *WithdrawUnsoldTokensRequest, opts ...grpc.CallOption) (*WithdrawUnsoldTokensResponse, error)
	DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignResponse, error)
	UpdateCampaignStatus(ctx context.Context, in *UpdateCampaignStatusRequest, opts ...grpc.CallOption) (*UpdateCampaignStatusResponse, error)
	CloseCampaignIfSoftCapNotReached(ctx context.Context, in *CloseCampaignIfSoftCapNotReachedRequest, opts ...grpc.CallOption) (*CloseCampaignIfSoftCapNotReachedResponse, error)
}

type campaignsClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignsClient(cc grpc.ClientConnInterface) CampaignsClient {
	return &campaignsClient{cc}
}

func (c *campaignsClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCampaignResponse)
	err := c.cc.Invoke(ctx, Campaigns_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) GetCampaignsList(ctx context.Context, in *GetCampaignsListRequest, opts ...grpc.CallOption) (*GetCampaignsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCampaignsListResponse)
	err := c.cc.Invoke(ctx, Campaigns_GetCampaignsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) DepositTokensToSale(ctx context.Context, in *DepositTokensToSaleRequest, opts ...grpc.CallOption) (*DepositTokensToSaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositTokensToSaleResponse)
	err := c.cc.Invoke(ctx, Campaigns_DepositTokensToSale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) JoinIdo(ctx context.Context, in *JoinIdoRequest, opts ...grpc.CallOption) (*JoinIdoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinIdoResponse)
	err := c.cc.Invoke(ctx, Campaigns_JoinIdo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, Campaigns_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, Campaigns_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) WithdrawFunds(ctx context.Context, in *WithdrawFundsRequest, opts ...grpc.CallOption) (*WithdrawFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawFundsResponse)
	err := c.cc.Invoke(ctx, Campaigns_WithdrawFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) CloseCampaign(ctx context.Context, in *CloseCampaignRequest, opts ...grpc.CallOption) (*CloseCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseCampaignResponse)
	err := c.cc.Invoke(ctx, Campaigns_CloseCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) WithdrawUnsoldTokens(ctx context.Context, in *WithdrawUnsoldTokensRequest, opts ...grpc.CallOption) (*WithdrawUnsoldTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawUnsoldTokensResponse)
	err := c.cc.Invoke(ctx, Campaigns_WithdrawUnsoldTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCampaignResponse)
	err := c.cc.Invoke(ctx, Campaigns_DeleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) UpdateCampaignStatus(ctx context.Context, in *UpdateCampaignStatusRequest, opts ...grpc.CallOption) (*UpdateCampaignStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCampaignStatusResponse)
	err := c.cc.Invoke(ctx, Campaigns_UpdateCampaignStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsClient) CloseCampaignIfSoftCapNotReached(ctx context.Context, in *CloseCampaignIfSoftCapNotReachedRequest, opts ...grpc.CallOption) (*CloseCampaignIfSoftCapNotReachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseCampaignIfSoftCapNotReachedResponse)
	err := c.cc.Invoke(ctx, Campaigns_CloseCampaignIfSoftCapNotReached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignsServer is the server API for Campaigns service.
// All implementations must embed UnimplementedCampaignsServer
// for forward compatibility.
type CampaignsServer interface {
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error)
	GetCampaignsList(context.Context, *GetCampaignsListRequest) (*GetCampaignsListResponse, error)
	DepositTokensToSale(context.Context, *DepositTokensToSaleRequest) (*DepositTokensToSaleResponse, error)
	JoinIdo(context.Context, *JoinIdoRequest) (*JoinIdoResponse, error)
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	WithdrawFunds(context.Context, *WithdrawFundsRequest) (*WithdrawFundsResponse, error)
	CloseCampaign(context.Context, *CloseCampaignRequest) (*CloseCampaignResponse, error)
	WithdrawUnsoldTokens(context.Context, *WithdrawUnsoldTokensRequest) (*WithdrawUnsoldTokensResponse, error)
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignResponse, error)
	UpdateCampaignStatus(context.Context, *UpdateCampaignStatusRequest) (*UpdateCampaignStatusResponse, error)
	CloseCampaignIfSoftCapNotReached(context.Context, *CloseCampaignIfSoftCapNotReachedRequest) (*CloseCampaignIfSoftCapNotReachedResponse, error)
	mustEmbedUnimplementedCampaignsServer()
}

// UnimplementedCampaignsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignsServer struct{}

func (UnimplementedCampaignsServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedCampaignsServer) GetCampaignsList(context.Context, *GetCampaignsListRequest) (*GetCampaignsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaignsList not implemented")
}
func (UnimplementedCampaignsServer) DepositTokensToSale(context.Context, *DepositTokensToSaleRequest) (*DepositTokensToSaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositTokensToSale not implemented")
}
func (UnimplementedCampaignsServer) JoinIdo(context.Context, *JoinIdoRequest) (*JoinIdoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinIdo not implemented")
}
func (UnimplementedCampaignsServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedCampaignsServer) Refund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedCampaignsServer) WithdrawFunds(context.Context, *WithdrawFundsRequest) (*WithdrawFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawFunds not implemented")
}
func (UnimplementedCampaignsServer) CloseCampaign(context.Context, *CloseCampaignRequest) (*CloseCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseCampaign not implemented")
}
func (UnimplementedCampaignsServer) WithdrawUnsoldTokens(context.Context, *WithdrawUnsoldTokensRequest) (*WithdrawUnsoldTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawUnsoldTokens not implemented")
}
func (UnimplementedCampaignsServer) DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCampaign not implemented")
}
func (UnimplementedCampaignsServer) UpdateCampaignStatus(context.Context, *UpdateCampaignStatusRequest) (*UpdateCampaignStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCampaignStatus not implemented")
}
func (UnimplementedCampaignsServer) CloseCampaignIfSoftCapNotReached(context.Context, *CloseCampaignIfSoftCapNotReachedRequest) (*CloseCampaignIfSoftCapNotReachedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseCampaignIfSoftCapNotReached not implemented")
}
func (UnimplementedCampaignsServer) mustEmbedUnimplementedCampaignsServer() {}
func (UnimplementedCampaignsServer) testEmbeddedByValue()                   {}

// UnsafeCampaignsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignsServer will
// result in compilation errors.
type UnsafeCampaignsServer interface {
	mustEmbedUnimplementedCampaignsServer()
}

func RegisterCampaignsServer(s grpc.ServiceRegistrar, srv CampaignsServer) {
	// If the following call pancis, it indicates UnimplementedCampaignsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Campaigns_ServiceDesc, srv)
}

func _Campaigns_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_GetCampaignsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).GetCampaignsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_GetCampaignsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).GetCampaignsList(ctx, req.(*GetCampaignsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_DepositTokensToSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositTokensToSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).DepositTokensToSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_DepositTokensToSale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).DepositTokensToSale(ctx, req.(*DepositTokensToSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_JoinIdo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinIdoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).JoinIdo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_JoinIdo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).JoinIdo(ctx, req.(*JoinIdoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_WithdrawFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).WithdrawFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_WithdrawFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).WithdrawFunds(ctx, req.(*WithdrawFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_CloseCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).CloseCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_CloseCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).CloseCampaign(ctx, req.(*CloseCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_WithdrawUnsoldTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawUnsoldTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).WithdrawUnsoldTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_WithdrawUnsoldTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).WithdrawUnsoldTokens(ctx, req.(*WithdrawUnsoldTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_DeleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).DeleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_DeleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_UpdateCampaignStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).UpdateCampaignStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_UpdateCampaignStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).UpdateCampaignStatus(ctx, req.(*UpdateCampaignStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Campaigns_CloseCampaignIfSoftCapNotReached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseCampaignIfSoftCapNotReachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).CloseCampaignIfSoftCapNotReached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Campaigns_CloseCampaignIfSoftCapNotReached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).CloseCampaignIfSoftCapNotReached(ctx, req.(*CloseCampaignIfSoftCapNotReachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Campaigns_ServiceDesc is the grpc.ServiceDesc for Campaigns service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Campaigns_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campaigns.public.Campaigns",
	HandlerType: (*CampaignsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _Campaigns_CreateCampaign_Handler,
		},
		{
			MethodName: "GetCampaignsList",
			Handler:    _Campaigns_GetCampaignsList_Handler,
		},
		{
			MethodName: "DepositTokensToSale",
			Handler:    _Campaigns_DepositTokensToSale_Handler,
		},
		{
			MethodName: "JoinIdo",
			Handler:    _Campaigns_JoinIdo_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _Campaigns_Claim_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _Campaigns_Refund_Handler,
		},
		{
			MethodName: "WithdrawFunds",
			Handler:    _Campaigns_WithdrawFunds_Handler,
		},
		{
			MethodName: "CloseCampaign",
			Handler:    _Campaigns_CloseCampaign_Handler,
		},
		{
			MethodName: "WithdrawUnsoldTokens",
			Handler:    _Campaigns_WithdrawUnsoldTokens_Handler,
		},
		{
			MethodName: "DeleteCampaign",
			Handler:    _Campaigns_DeleteCampaign_Handler,
		},
		{
			MethodName: "UpdateCampaignStatus",
			Handler:    _Campaigns_UpdateCampaignStatus_Handler,
		},
		{
			MethodName: "CloseCampaignIfSoftCapNotReached",
			Handler:    _Campaigns_CloseCampaignIfSoftCapNotReached_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaigns.public.proto",
}
