// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: campaigns.public.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampaignStatus int32

const (
	CampaignStatus_CAMPAIGN_STATUS_UNDEFINED             CampaignStatus = 0
	CampaignStatus_CAMPAIGN_STATUS_TOKENS_NOT_DEPOSITED  CampaignStatus = 1
	CampaignStatus_CAMPAIGN_STATUS_WAITING_FOR_START     CampaignStatus = 2
	CampaignStatus_CAMPAIGN_STATUS_SALE_STARTED          CampaignStatus = 3
	CampaignStatus_CAMPAIGN_STATUS_SALE_ENDED_SUCCESSFUL CampaignStatus = 4
	CampaignStatus_CAMPAIGN_STATUS_SALE_ENDED_FAILED     CampaignStatus = 5
	CampaignStatus_CAMPAIGN_STATUS_SALE_CLOSED_BY_OWNER  CampaignStatus = 6
	CampaignStatus_CAMPAIGN_STATUS_FUNDS_WITHDRAWN       CampaignStatus = 7
)

// Enum value maps for CampaignStatus.
var (
	CampaignStatus_name = map[int32]string{
		0: "CAMPAIGN_STATUS_UNDEFINED",
		1: "CAMPAIGN_STATUS_TOKENS_NOT_DEPOSITED",
		2: "CAMPAIGN_STATUS_WAITING_FOR_START",
		3: "CAMPAIGN_STATUS_SALE_STARTED",
		4: "CAMPAIGN_STATUS_SALE_ENDED_SUCCESSFUL",
		5: "CAMPAIGN_STATUS_SALE_ENDED_FAILED",
		6: "CAMPAIGN_STATUS_SALE_CLOSED_BY_OWNER",
		7: "CAMPAIGN_STATUS_FUNDS_WITHDRAWN",
	}
	CampaignStatus_value = map[string]int32{
		"CAMPAIGN_STATUS_UNDEFINED":             0,
		"CAMPAIGN_STATUS_TOKENS_NOT_DEPOSITED":  1,
		"CAMPAIGN_STATUS_WAITING_FOR_START":     2,
		"CAMPAIGN_STATUS_SALE_STARTED":          3,
		"CAMPAIGN_STATUS_SALE_ENDED_SUCCESSFUL": 4,
		"CAMPAIGN_STATUS_SALE_ENDED_FAILED":     5,
		"CAMPAIGN_STATUS_SALE_CLOSED_BY_OWNER":  6,
		"CAMPAIGN_STATUS_FUNDS_WITHDRAWN":       7,
	}
)

func (x CampaignStatus) Enum() *CampaignStatus {
	p := new(CampaignStatus)
	*p = x
	return p
}

func (x CampaignStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CampaignStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_campaigns_public_proto_enumTypes[0].Descriptor()
}

func (CampaignStatus) Type() protoreflect.EnumType {
	return &file_campaigns_public_proto_enumTypes[0]
}

func (x CampaignStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CampaignStatus.Descriptor instead.
func (CampaignStatus) EnumDescriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{0}
}

type CreateCampaignRequest struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	CampaignId                         uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AuthorityPubkey                    string                 `protobuf:"bytes,2,opt,name=authority_pubkey,json=authorityPubkey,proto3" json:"authority_pubkey,omitempty"`
	TokenMintPubkey                    string                 `protobuf:"bytes,3,opt,name=token_mint_pubkey,json=tokenMintPubkey,proto3" json:"token_mint_pubkey,omitempty"`
	Cliff                              int64                  `protobuf:"varint,4,opt,name=cliff,proto3" json:"cliff,omitempty"`
	AvailableTokensAfterCliffPtc       uint32                 `protobuf:"varint,5,opt,name=available_tokens_after_cliff_ptc,json=availableTokensAfterCliffPtc,proto3" json:"available_tokens_after_cliff_ptc,omitempty"`
	StartSaleTime                      int64                  `protobuf:"varint,6,opt,name=start_sale_time,json=startSaleTime,proto3" json:"start_sale_time,omitempty"`
	EndSaleTime                        int64                  `protobuf:"varint,7,opt,name=end_sale_time,json=endSaleTime,proto3" json:"end_sale_time,omitempty"`
	VestingEndTime                     int64                  `protobuf:"varint,8,opt,name=vesting_end_time,json=vestingEndTime,proto3" json:"vesting_end_time,omitempty"`
	PricePerTokenLamports              uint64                 `protobuf:"varint,9,opt,name=price_per_token_lamports,json=pricePerTokenLamports,proto3" json:"price_per_token_lamports,omitempty"`
	AllocationSize                     int64                  `protobuf:"varint,10,opt,name=allocation_size,json=allocationSize,proto3" json:"allocation_size,omitempty"`
	SoftCap                            uint64                 `protobuf:"varint,11,opt,name=soft_cap,json=softCap,proto3" json:"soft_cap,omitempty"`
	HardCap                            uint64                 `protobuf:"varint,12,opt,name=hard_cap,json=hardCap,proto3" json:"hard_cap,omitempty"`
	AvailableAllocationsPerParticipant uint64                 `protobuf:"varint,13,opt,name=available_allocations_per_participant,json=availableAllocationsPerParticipant,proto3" json:"available_allocations_per_participant,omitempty"`
	CampaignName                       string                 `protobuf:"bytes,14,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	Description                        string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	Ticker                             string                 `protobuf:"bytes,16,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_campaigns_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCampaignRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *CreateCampaignRequest) GetAuthorityPubkey() string {
	if x != nil {
		return x.AuthorityPubkey
	}
	return ""
}

func (x *CreateCampaignRequest) GetTokenMintPubkey() string {
	if x != nil {
		return x.TokenMintPubkey
	}
	return ""
}

func (x *CreateCampaignRequest) GetCliff() int64 {
	if x != nil {
		return x.Cliff
	}
	return 0
}

func (x *CreateCampaignRequest) GetAvailableTokensAfterCliffPtc() uint32 {
	if x != nil {
		return x.AvailableTokensAfterCliffPtc
	}
	return 0
}

func (x *CreateCampaignRequest) GetStartSaleTime() int64 {
	if x != nil {
		return x.StartSaleTime
	}
	return 0
}

func (x *CreateCampaignRequest) GetEndSaleTime() int64 {
	if x != nil {
		return x.EndSaleTime
	}
	return 0
}

func (x *CreateCampaignRequest) GetVestingEndTime() int64 {
	if x != nil {
		return x.VestingEndTime
	}
	return 0
}

func (x *CreateCampaignRequest) GetPricePerTokenLamports() uint64 {
	if x != nil {
		return x.PricePerTokenLamports
	}
	return 0
}

func (x *CreateCampaignRequest) GetAllocationSize() int64 {
	if x != nil {
		return x.AllocationSize
	}
	return 0
}

func (x *CreateCampaignRequest) GetSoftCap() uint64 {
	if x != nil {
		return x.SoftCap
	}
	return 0
}

func (x *CreateCampaignRequest) GetHardCap() uint64 {
	if x != nil {
		return x.HardCap
	}
	return 0
}

func (x *CreateCampaignRequest) GetAvailableAllocationsPerParticipant() uint64 {
	if x != nil {
		return x.AvailableAllocationsPerParticipant
	}
	return 0
}

func (x *CreateCampaignRequest) GetCampaignName() string {
	if x != nil {
		return x.CampaignName
	}
	return ""
}

func (x *CreateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type CreateCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse) Reset() {
	*x = CreateCampaignResponse{}
	mi := &file_campaigns_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse) ProtoMessage() {}

func (x *CreateCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCampaignResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCampaignsListRequest struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	Id                                     uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId                             uint64                 `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AuthorityPubkey                        string                 `protobuf:"bytes,3,opt,name=authority_pubkey,json=authorityPubkey,proto3" json:"authority_pubkey,omitempty"`
	TokenMintPubkey                        string                 `protobuf:"bytes,4,opt,name=token_mint_pubkey,json=tokenMintPubkey,proto3" json:"token_mint_pubkey,omitempty"`
	CliffFrom                              int64                  `protobuf:"varint,5,opt,name=cliff_from,json=cliffFrom,proto3" json:"cliff_from,omitempty"`
	CliffTo                                int64                  `protobuf:"varint,6,opt,name=cliff_to,json=cliffTo,proto3" json:"cliff_to,omitempty"`
	AvailableTokensAfterCliffPtcFrom       int32                  `protobuf:"varint,7,opt,name=available_tokens_after_cliff_ptc_from,json=availableTokensAfterCliffPtcFrom,proto3" json:"available_tokens_after_cliff_ptc_from,omitempty"`
	AvailableTokensAfterCliffPtcTo         int32                  `protobuf:"varint,8,opt,name=available_tokens_after_cliff_ptc_to,json=availableTokensAfterCliffPtcTo,proto3" json:"available_tokens_after_cliff_ptc_to,omitempty"`
	StartSaleTime                          int64                  `protobuf:"varint,9,opt,name=start_sale_time,json=startSaleTime,proto3" json:"start_sale_time,omitempty"`
	EndSaleTime                            int64                  `protobuf:"varint,10,opt,name=end_sale_time,json=endSaleTime,proto3" json:"end_sale_time,omitempty"`
	VestingEndTimeFrom                     int64                  `protobuf:"varint,11,opt,name=vesting_end_time_from,json=vestingEndTimeFrom,proto3" json:"vesting_end_time_from,omitempty"`
	VestingEndTimeTo                       int64                  `protobuf:"varint,12,opt,name=vesting_end_time_to,json=vestingEndTimeTo,proto3" json:"vesting_end_time_to,omitempty"`
	PricePerTokenLamportsFrom              uint64                 `protobuf:"varint,13,opt,name=price_per_token_lamports_from,json=pricePerTokenLamportsFrom,proto3" json:"price_per_token_lamports_from,omitempty"`
	PricePerTokenLamportsTo                uint64                 `protobuf:"varint,14,opt,name=price_per_token_lamports_to,json=pricePerTokenLamportsTo,proto3" json:"price_per_token_lamports_to,omitempty"`
	AllocationSizeFrom                     int64                  `protobuf:"varint,15,opt,name=allocation_size_from,json=allocationSizeFrom,proto3" json:"allocation_size_from,omitempty"`
	AllocationSizeTo                       int64                  `protobuf:"varint,16,opt,name=allocation_size_to,json=allocationSizeTo,proto3" json:"allocation_size_to,omitempty"`
	SoftCapFrom                            uint64                 `protobuf:"varint,17,opt,name=soft_cap_from,json=softCapFrom,proto3" json:"soft_cap_from,omitempty"`
	SoftCapTo                              uint64                 `protobuf:"varint,18,opt,name=soft_cap_to,json=softCapTo,proto3" json:"soft_cap_to,omitempty"`
	HardCapFrom                            uint64                 `protobuf:"varint,19,opt,name=hard_cap_from,json=hardCapFrom,proto3" json:"hard_cap_from,omitempty"`
	HardCapTo                              uint64                 `protobuf:"varint,20,opt,name=hard_cap_to,json=hardCapTo,proto3" json:"hard_cap_to,omitempty"`
	AvailableAllocationsPerParticipantFrom uint64                 `protobuf:"varint,21,opt,name=available_allocations_per_participant_from,json=availableAllocationsPerParticipantFrom,proto3" json:"available_allocations_per_participant_from,omitempty"`
	AvailableAllocationsPerParticipantTo   uint64                 `protobuf:"varint,22,opt,name=available_allocations_per_participant_to,json=availableAllocationsPerParticipantTo,proto3" json:"available_allocations_per_participant_to,omitempty"`
	CampaignStatus                         CampaignStatus         `protobuf:"varint,23,opt,name=campaign_status,json=campaignStatus,proto3,enum=campaigns.public.CampaignStatus" json:"campaign_status,omitempty"`
	ParticipantId                          uint64                 `protobuf:"varint,24,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	CreatedAtFrom                          int64                  `protobuf:"varint,25,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`
	CreatedAtTo                            int64                  `protobuf:"varint,26,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`
	UpdatedAtFrom                          int64                  `protobuf:"varint,27,opt,name=updated_at_from,json=updatedAtFrom,proto3" json:"updated_at_from,omitempty"`
	UpdatedAtTo                            int64                  `protobuf:"varint,28,opt,name=updated_at_to,json=updatedAtTo,proto3" json:"updated_at_to,omitempty"`
	Page                                   uint32                 `protobuf:"varint,29,opt,name=page,proto3" json:"page,omitempty"`
	Limit                                  uint32                 `protobuf:"varint,30,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *GetCampaignsListRequest) Reset() {
	*x = GetCampaignsListRequest{}
	mi := &file_campaigns_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsListRequest) ProtoMessage() {}

func (x *GetCampaignsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsListRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignsListRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{2}
}

func (x *GetCampaignsListRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCampaignsListRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAuthorityPubkey() string {
	if x != nil {
		return x.AuthorityPubkey
	}
	return ""
}

func (x *GetCampaignsListRequest) GetTokenMintPubkey() string {
	if x != nil {
		return x.TokenMintPubkey
	}
	return ""
}

func (x *GetCampaignsListRequest) GetCliffFrom() int64 {
	if x != nil {
		return x.CliffFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetCliffTo() int64 {
	if x != nil {
		return x.CliffTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAvailableTokensAfterCliffPtcFrom() int32 {
	if x != nil {
		return x.AvailableTokensAfterCliffPtcFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAvailableTokensAfterCliffPtcTo() int32 {
	if x != nil {
		return x.AvailableTokensAfterCliffPtcTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetStartSaleTime() int64 {
	if x != nil {
		return x.StartSaleTime
	}
	return 0
}

func (x *GetCampaignsListRequest) GetEndSaleTime() int64 {
	if x != nil {
		return x.EndSaleTime
	}
	return 0
}

func (x *GetCampaignsListRequest) GetVestingEndTimeFrom() int64 {
	if x != nil {
		return x.VestingEndTimeFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetVestingEndTimeTo() int64 {
	if x != nil {
		return x.VestingEndTimeTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetPricePerTokenLamportsFrom() uint64 {
	if x != nil {
		return x.PricePerTokenLamportsFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetPricePerTokenLamportsTo() uint64 {
	if x != nil {
		return x.PricePerTokenLamportsTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAllocationSizeFrom() int64 {
	if x != nil {
		return x.AllocationSizeFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAllocationSizeTo() int64 {
	if x != nil {
		return x.AllocationSizeTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetSoftCapFrom() uint64 {
	if x != nil {
		return x.SoftCapFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetSoftCapTo() uint64 {
	if x != nil {
		return x.SoftCapTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetHardCapFrom() uint64 {
	if x != nil {
		return x.HardCapFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetHardCapTo() uint64 {
	if x != nil {
		return x.HardCapTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAvailableAllocationsPerParticipantFrom() uint64 {
	if x != nil {
		return x.AvailableAllocationsPerParticipantFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetAvailableAllocationsPerParticipantTo() uint64 {
	if x != nil {
		return x.AvailableAllocationsPerParticipantTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetCampaignStatus() CampaignStatus {
	if x != nil {
		return x.CampaignStatus
	}
	return CampaignStatus_CAMPAIGN_STATUS_UNDEFINED
}

func (x *GetCampaignsListRequest) GetParticipantId() uint64 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

func (x *GetCampaignsListRequest) GetCreatedAtFrom() int64 {
	if x != nil {
		return x.CreatedAtFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetCreatedAtTo() int64 {
	if x != nil {
		return x.CreatedAtTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetUpdatedAtFrom() int64 {
	if x != nil {
		return x.UpdatedAtFrom
	}
	return 0
}

func (x *GetCampaignsListRequest) GetUpdatedAtTo() int64 {
	if x != nil {
		return x.UpdatedAtTo
	}
	return 0
}

func (x *GetCampaignsListRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCampaignsListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCampaignsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignsListResponse) Reset() {
	*x = GetCampaignsListResponse{}
	mi := &file_campaigns_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsListResponse) ProtoMessage() {}

func (x *GetCampaignsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsListResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignsListResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{3}
}

func (x *GetCampaignsListResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *GetCampaignsListResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    uint64                 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   uint32                 `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_campaigns_public_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pagination) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetCurrentPage() uint32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Campaign struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	Id                                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId                         uint64                 `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AuthorityPubkey                    string                 `protobuf:"bytes,3,opt,name=authority_pubkey,json=authorityPubkey,proto3" json:"authority_pubkey,omitempty"`
	TokenMintPubkey                    string                 `protobuf:"bytes,4,opt,name=token_mint_pubkey,json=tokenMintPubkey,proto3" json:"token_mint_pubkey,omitempty"`
	Cliff                              int64                  `protobuf:"varint,5,opt,name=cliff,proto3" json:"cliff,omitempty"`
	AvailableTokensAfterCliffPtc       uint32                 `protobuf:"varint,6,opt,name=available_tokens_after_cliff_ptc,json=availableTokensAfterCliffPtc,proto3" json:"available_tokens_after_cliff_ptc,omitempty"`
	StartSaleTime                      int64                  `protobuf:"varint,7,opt,name=start_sale_time,json=startSaleTime,proto3" json:"start_sale_time,omitempty"`
	EndSaleTime                        int64                  `protobuf:"varint,8,opt,name=end_sale_time,json=endSaleTime,proto3" json:"end_sale_time,omitempty"`
	VestingEndTime                     int64                  `protobuf:"varint,9,opt,name=vesting_end_time,json=vestingEndTime,proto3" json:"vesting_end_time,omitempty"`
	PricePerTokenLamports              uint64                 `protobuf:"varint,10,opt,name=price_per_token_lamports,json=pricePerTokenLamports,proto3" json:"price_per_token_lamports,omitempty"`
	AllocationSize                     int64                  `protobuf:"varint,11,opt,name=allocation_size,json=allocationSize,proto3" json:"allocation_size,omitempty"`
	SoftCap                            uint64                 `protobuf:"varint,12,opt,name=soft_cap,json=softCap,proto3" json:"soft_cap,omitempty"`
	HardCap                            uint64                 `protobuf:"varint,13,opt,name=hard_cap,json=hardCap,proto3" json:"hard_cap,omitempty"`
	AvailableAllocationsPerParticipant uint64                 `protobuf:"varint,14,opt,name=available_allocations_per_participant,json=availableAllocationsPerParticipant,proto3" json:"available_allocations_per_participant,omitempty"`
	CampaignStatus                     CampaignStatus         `protobuf:"varint,15,opt,name=campaign_status,json=campaignStatus,proto3,enum=campaigns.public.CampaignStatus" json:"campaign_status,omitempty"`
	CreatedAt                          int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TotalParticipants                  uint32                 `protobuf:"varint,17,opt,name=total_participants,json=totalParticipants,proto3" json:"total_participants,omitempty"`
	TotalClaimed                       uint64                 `protobuf:"varint,18,opt,name=total_claimed,json=totalClaimed,proto3" json:"total_claimed,omitempty"`
	TotalSold                          uint64                 `protobuf:"varint,19,opt,name=total_sold,json=totalSold,proto3" json:"total_sold,omitempty"`
	CampaignName                       string                 `protobuf:"bytes,20,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	Description                        string                 `protobuf:"bytes,21,opt,name=description,proto3" json:"description,omitempty"`
	Ticker                             string                 `protobuf:"bytes,22,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_campaigns_public_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{5}
}

func (x *Campaign) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Campaign) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *Campaign) GetAuthorityPubkey() string {
	if x != nil {
		return x.AuthorityPubkey
	}
	return ""
}

func (x *Campaign) GetTokenMintPubkey() string {
	if x != nil {
		return x.TokenMintPubkey
	}
	return ""
}

func (x *Campaign) GetCliff() int64 {
	if x != nil {
		return x.Cliff
	}
	return 0
}

func (x *Campaign) GetAvailableTokensAfterCliffPtc() uint32 {
	if x != nil {
		return x.AvailableTokensAfterCliffPtc
	}
	return 0
}

func (x *Campaign) GetStartSaleTime() int64 {
	if x != nil {
		return x.StartSaleTime
	}
	return 0
}

func (x *Campaign) GetEndSaleTime() int64 {
	if x != nil {
		return x.EndSaleTime
	}
	return 0
}

func (x *Campaign) GetVestingEndTime() int64 {
	if x != nil {
		return x.VestingEndTime
	}
	return 0
}

func (x *Campaign) GetPricePerTokenLamports() uint64 {
	if x != nil {
		return x.PricePerTokenLamports
	}
	return 0
}

func (x *Campaign) GetAllocationSize() int64 {
	if x != nil {
		return x.AllocationSize
	}
	return 0
}

func (x *Campaign) GetSoftCap() uint64 {
	if x != nil {
		return x.SoftCap
	}
	return 0
}

func (x *Campaign) GetHardCap() uint64 {
	if x != nil {
		return x.HardCap
	}
	return 0
}

func (x *Campaign) GetAvailableAllocationsPerParticipant() uint64 {
	if x != nil {
		return x.AvailableAllocationsPerParticipant
	}
	return 0
}

func (x *Campaign) GetCampaignStatus() CampaignStatus {
	if x != nil {
		return x.CampaignStatus
	}
	return CampaignStatus_CAMPAIGN_STATUS_UNDEFINED
}

func (x *Campaign) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Campaign) GetTotalParticipants() uint32 {
	if x != nil {
		return x.TotalParticipants
	}
	return 0
}

func (x *Campaign) GetTotalClaimed() uint64 {
	if x != nil {
		return x.TotalClaimed
	}
	return 0
}

func (x *Campaign) GetTotalSold() uint64 {
	if x != nil {
		return x.TotalSold
	}
	return 0
}

func (x *Campaign) GetCampaignName() string {
	if x != nil {
		return x.CampaignName
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type DepositTokensToSaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTokensToSaleRequest) Reset() {
	*x = DepositTokensToSaleRequest{}
	mi := &file_campaigns_public_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTokensToSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTokensToSaleRequest) ProtoMessage() {}

func (x *DepositTokensToSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTokensToSaleRequest.ProtoReflect.Descriptor instead.
func (*DepositTokensToSaleRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{6}
}

func (x *DepositTokensToSaleRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type DepositTokensToSaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTokensToSaleResponse) Reset() {
	*x = DepositTokensToSaleResponse{}
	mi := &file_campaigns_public_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTokensToSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTokensToSaleResponse) ProtoMessage() {}

func (x *DepositTokensToSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTokensToSaleResponse.ProtoReflect.Descriptor instead.
func (*DepositTokensToSaleResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{7}
}

type JoinIdoRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CampaignId          uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ParticipantPubkey   string                 `protobuf:"bytes,2,opt,name=participant_pubkey,json=participantPubkey,proto3" json:"participant_pubkey,omitempty"`
	NumberOfAllocations uint64                 `protobuf:"varint,3,opt,name=number_of_allocations,json=numberOfAllocations,proto3" json:"number_of_allocations,omitempty"`
	Amount              int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaidLamports        int64                  `protobuf:"varint,5,opt,name=paid_lamports,json=paidLamports,proto3" json:"paid_lamports,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JoinIdoRequest) Reset() {
	*x = JoinIdoRequest{}
	mi := &file_campaigns_public_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinIdoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinIdoRequest) ProtoMessage() {}

func (x *JoinIdoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinIdoRequest.ProtoReflect.Descriptor instead.
func (*JoinIdoRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{8}
}

func (x *JoinIdoRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *JoinIdoRequest) GetParticipantPubkey() string {
	if x != nil {
		return x.ParticipantPubkey
	}
	return ""
}

func (x *JoinIdoRequest) GetNumberOfAllocations() uint64 {
	if x != nil {
		return x.NumberOfAllocations
	}
	return 0
}

func (x *JoinIdoRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *JoinIdoRequest) GetPaidLamports() int64 {
	if x != nil {
		return x.PaidLamports
	}
	return 0
}

type JoinIdoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinIdoResponse) Reset() {
	*x = JoinIdoResponse{}
	mi := &file_campaigns_public_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinIdoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinIdoResponse) ProtoMessage() {}

func (x *JoinIdoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinIdoResponse.ProtoReflect.Descriptor instead.
func (*JoinIdoResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{9}
}

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ClaimedAmount int64                  `protobuf:"varint,2,opt,name=claimed_amount,json=claimedAmount,proto3" json:"claimed_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_campaigns_public_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *ClaimRequest) GetClaimedAmount() int64 {
	if x != nil {
		return x.ClaimedAmount
	}
	return 0
}

type ClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_campaigns_public_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{11}
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_campaigns_public_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{12}
}

func (x *RefundRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_campaigns_public_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{13}
}

type WithdrawFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawFundsRequest) Reset() {
	*x = WithdrawFundsRequest{}
	mi := &file_campaigns_public_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawFundsRequest) ProtoMessage() {}

func (x *WithdrawFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawFundsRequest.ProtoReflect.Descriptor instead.
func (*WithdrawFundsRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{14}
}

func (x *WithdrawFundsRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type WithdrawFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawFundsResponse) Reset() {
	*x = WithdrawFundsResponse{}
	mi := &file_campaigns_public_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawFundsResponse) ProtoMessage() {}

func (x *WithdrawFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawFundsResponse.ProtoReflect.Descriptor instead.
func (*WithdrawFundsResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{15}
}

type CloseCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCampaignRequest) Reset() {
	*x = CloseCampaignRequest{}
	mi := &file_campaigns_public_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCampaignRequest) ProtoMessage() {}

func (x *CloseCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCampaignRequest.ProtoReflect.Descriptor instead.
func (*CloseCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{16}
}

func (x *CloseCampaignRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type CloseCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCampaignResponse) Reset() {
	*x = CloseCampaignResponse{}
	mi := &file_campaigns_public_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCampaignResponse) ProtoMessage() {}

func (x *CloseCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCampaignResponse.ProtoReflect.Descriptor instead.
func (*CloseCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{17}
}

type WithdrawUnsoldTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawUnsoldTokensRequest) Reset() {
	*x = WithdrawUnsoldTokensRequest{}
	mi := &file_campaigns_public_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawUnsoldTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawUnsoldTokensRequest) ProtoMessage() {}

func (x *WithdrawUnsoldTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawUnsoldTokensRequest.ProtoReflect.Descriptor instead.
func (*WithdrawUnsoldTokensRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{18}
}

func (x *WithdrawUnsoldTokensRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type WithdrawUnsoldTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawUnsoldTokensResponse) Reset() {
	*x = WithdrawUnsoldTokensResponse{}
	mi := &file_campaigns_public_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawUnsoldTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawUnsoldTokensResponse) ProtoMessage() {}

func (x *WithdrawUnsoldTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawUnsoldTokensResponse.ProtoReflect.Descriptor instead.
func (*WithdrawUnsoldTokensResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{19}
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_campaigns_public_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCampaignRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_campaigns_public_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{21}
}

type UpdateCampaignStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Status        CampaignStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=campaigns.public.CampaignStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignStatusRequest) Reset() {
	*x = UpdateCampaignStatusRequest{}
	mi := &file_campaigns_public_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignStatusRequest) ProtoMessage() {}

func (x *UpdateCampaignStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignStatusRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateCampaignStatusRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *UpdateCampaignStatusRequest) GetStatus() CampaignStatus {
	if x != nil {
		return x.Status
	}
	return CampaignStatus_CAMPAIGN_STATUS_UNDEFINED
}

type UpdateCampaignStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignStatusResponse) Reset() {
	*x = UpdateCampaignStatusResponse{}
	mi := &file_campaigns_public_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignStatusResponse) ProtoMessage() {}

func (x *UpdateCampaignStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCampaignStatusResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{23}
}

type CloseCampaignIfSoftCapNotReachedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint64                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCampaignIfSoftCapNotReachedRequest) Reset() {
	*x = CloseCampaignIfSoftCapNotReachedRequest{}
	mi := &file_campaigns_public_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCampaignIfSoftCapNotReachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCampaignIfSoftCapNotReachedRequest) ProtoMessage() {}

func (x *CloseCampaignIfSoftCapNotReachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCampaignIfSoftCapNotReachedRequest.ProtoReflect.Descriptor instead.
func (*CloseCampaignIfSoftCapNotReachedRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{24}
}

func (x *CloseCampaignIfSoftCapNotReachedRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type CloseCampaignIfSoftCapNotReachedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCampaignIfSoftCapNotReachedResponse) Reset() {
	*x = CloseCampaignIfSoftCapNotReachedResponse{}
	mi := &file_campaigns_public_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCampaignIfSoftCapNotReachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCampaignIfSoftCapNotReachedResponse) ProtoMessage() {}

func (x *CloseCampaignIfSoftCapNotReachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_public_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCampaignIfSoftCapNotReachedResponse.ProtoReflect.Descriptor instead.
func (*CloseCampaignIfSoftCapNotReachedResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_public_proto_rawDescGZIP(), []int{25}
}

var File_campaigns_public_proto protoreflect.FileDescriptor

const file_campaigns_public_proto_rawDesc = "" +
	"\n" +
	"\x16campaigns.public.proto\x12\x10campaigns.public\"\xad\x05\n" +
	"\x15CreateCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\x12)\n" +
	"\x10authority_pubkey\x18\x02 \x01(\tR\x0fauthorityPubkey\x12*\n" +
	"\x11token_mint_pubkey\x18\x03 \x01(\tR\x0ftokenMintPubkey\x12\x14\n" +
	"\x05cliff\x18\x04 \x01(\x03R\x05cliff\x12F\n" +
	" available_tokens_after_cliff_ptc\x18\x05 \x01(\rR\x1cavailableTokensAfterCliffPtc\x12&\n" +
	"\x0fstart_sale_time\x18\x06 \x01(\x03R\rstartSaleTime\x12\"\n" +
	"\rend_sale_time\x18\a \x01(\x03R\vendSaleTime\x12(\n" +
	"\x10vesting_end_time\x18\b \x01(\x03R\x0evestingEndTime\x127\n" +
	"\x18price_per_token_lamports\x18\t \x01(\x04R\x15pricePerTokenLamports\x12'\n" +
	"\x0fallocation_size\x18\n" +
	" \x01(\x03R\x0eallocationSize\x12\x19\n" +
	"\bsoft_cap\x18\v \x01(\x04R\asoftCap\x12\x19\n" +
	"\bhard_cap\x18\f \x01(\x04R\ahardCap\x12Q\n" +
	"%available_allocations_per_participant\x18\r \x01(\x04R\"availableAllocationsPerParticipant\x12#\n" +
	"\rcampaign_name\x18\x0e \x01(\tR\fcampaignName\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\x12\x16\n" +
	"\x06ticker\x18\x10 \x01(\tR\x06ticker\"(\n" +
	"\x16CreateCampaignResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xf7\n" +
	"\n" +
	"\x17GetCampaignsListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\x04R\n" +
	"campaignId\x12)\n" +
	"\x10authority_pubkey\x18\x03 \x01(\tR\x0fauthorityPubkey\x12*\n" +
	"\x11token_mint_pubkey\x18\x04 \x01(\tR\x0ftokenMintPubkey\x12\x1d\n" +
	"\n" +
	"cliff_from\x18\x05 \x01(\x03R\tcliffFrom\x12\x19\n" +
	"\bcliff_to\x18\x06 \x01(\x03R\acliffTo\x12O\n" +
	"%available_tokens_after_cliff_ptc_from\x18\a \x01(\x05R availableTokensAfterCliffPtcFrom\x12K\n" +
	"#available_tokens_after_cliff_ptc_to\x18\b \x01(\x05R\x1eavailableTokensAfterCliffPtcTo\x12&\n" +
	"\x0fstart_sale_time\x18\t \x01(\x03R\rstartSaleTime\x12\"\n" +
	"\rend_sale_time\x18\n" +
	" \x01(\x03R\vendSaleTime\x121\n" +
	"\x15vesting_end_time_from\x18\v \x01(\x03R\x12vestingEndTimeFrom\x12-\n" +
	"\x13vesting_end_time_to\x18\f \x01(\x03R\x10vestingEndTimeTo\x12@\n" +
	"\x1dprice_per_token_lamports_from\x18\r \x01(\x04R\x19pricePerTokenLamportsFrom\x12<\n" +
	"\x1bprice_per_token_lamports_to\x18\x0e \x01(\x04R\x17pricePerTokenLamportsTo\x120\n" +
	"\x14allocation_size_from\x18\x0f \x01(\x03R\x12allocationSizeFrom\x12,\n" +
	"\x12allocation_size_to\x18\x10 \x01(\x03R\x10allocationSizeTo\x12\"\n" +
	"\rsoft_cap_from\x18\x11 \x01(\x04R\vsoftCapFrom\x12\x1e\n" +
	"\vsoft_cap_to\x18\x12 \x01(\x04R\tsoftCapTo\x12\"\n" +
	"\rhard_cap_from\x18\x13 \x01(\x04R\vhardCapFrom\x12\x1e\n" +
	"\vhard_cap_to\x18\x14 \x01(\x04R\thardCapTo\x12Z\n" +
	"*available_allocations_per_participant_from\x18\x15 \x01(\x04R&availableAllocationsPerParticipantFrom\x12V\n" +
	"(available_allocations_per_participant_to\x18\x16 \x01(\x04R$availableAllocationsPerParticipantTo\x12I\n" +
	"\x0fcampaign_status\x18\x17 \x01(\x0e2 .campaigns.public.CampaignStatusR\x0ecampaignStatus\x12%\n" +
	"\x0eparticipant_id\x18\x18 \x01(\x04R\rparticipantId\x12&\n" +
	"\x0fcreated_at_from\x18\x19 \x01(\x03R\rcreatedAtFrom\x12\"\n" +
	"\rcreated_at_to\x18\x1a \x01(\x03R\vcreatedAtTo\x12&\n" +
	"\x0fupdated_at_from\x18\x1b \x01(\x03R\rupdatedAtFrom\x12\"\n" +
	"\rupdated_at_to\x18\x1c \x01(\x03R\vupdatedAtTo\x12\x12\n" +
	"\x04page\x18\x1d \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x1e \x01(\rR\x05limit\"\x92\x01\n" +
	"\x18GetCampaignsListResponse\x128\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x1a.campaigns.public.CampaignR\tcampaigns\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.campaigns.public.PaginationR\n" +
	"pagination\"\x87\x01\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x04R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\rR\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\rR\vcurrentPage\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"\x8d\a\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\x04R\n" +
	"campaignId\x12)\n" +
	"\x10authority_pubkey\x18\x03 \x01(\tR\x0fauthorityPubkey\x12*\n" +
	"\x11token_mint_pubkey\x18\x04 \x01(\tR\x0ftokenMintPubkey\x12\x14\n" +
	"\x05cliff\x18\x05 \x01(\x03R\x05cliff\x12F\n" +
	" available_tokens_after_cliff_ptc\x18\x06 \x01(\rR\x1cavailableTokensAfterCliffPtc\x12&\n" +
	"\x0fstart_sale_time\x18\a \x01(\x03R\rstartSaleTime\x12\"\n" +
	"\rend_sale_time\x18\b \x01(\x03R\vendSaleTime\x12(\n" +
	"\x10vesting_end_time\x18\t \x01(\x03R\x0evestingEndTime\x127\n" +
	"\x18price_per_token_lamports\x18\n" +
	" \x01(\x04R\x15pricePerTokenLamports\x12'\n" +
	"\x0fallocation_size\x18\v \x01(\x03R\x0eallocationSize\x12\x19\n" +
	"\bsoft_cap\x18\f \x01(\x04R\asoftCap\x12\x19\n" +
	"\bhard_cap\x18\r \x01(\x04R\ahardCap\x12Q\n" +
	"%available_allocations_per_participant\x18\x0e \x01(\x04R\"availableAllocationsPerParticipant\x12I\n" +
	"\x0fcampaign_status\x18\x0f \x01(\x0e2 .campaigns.public.CampaignStatusR\x0ecampaignStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12-\n" +
	"\x12total_participants\x18\x11 \x01(\rR\x11totalParticipants\x12#\n" +
	"\rtotal_claimed\x18\x12 \x01(\x04R\ftotalClaimed\x12\x1d\n" +
	"\n" +
	"total_sold\x18\x13 \x01(\x04R\ttotalSold\x12#\n" +
	"\rcampaign_name\x18\x14 \x01(\tR\fcampaignName\x12 \n" +
	"\vdescription\x18\x15 \x01(\tR\vdescription\x12\x16\n" +
	"\x06ticker\x18\x16 \x01(\tR\x06ticker\"=\n" +
	"\x1aDepositTokensToSaleRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"\x1d\n" +
	"\x1bDepositTokensToSaleResponse\"\xd1\x01\n" +
	"\x0eJoinIdoRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\x12-\n" +
	"\x12participant_pubkey\x18\x02 \x01(\tR\x11participantPubkey\x122\n" +
	"\x15number_of_allocations\x18\x03 \x01(\x04R\x13numberOfAllocations\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12#\n" +
	"\rpaid_lamports\x18\x05 \x01(\x03R\fpaidLamports\"\x11\n" +
	"\x0fJoinIdoResponse\"V\n" +
	"\fClaimRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\x12%\n" +
	"\x0eclaimed_amount\x18\x02 \x01(\x03R\rclaimedAmount\"\x0f\n" +
	"\rClaimResponse\"0\n" +
	"\rRefundRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"\x10\n" +
	"\x0eRefundResponse\"7\n" +
	"\x14WithdrawFundsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"\x17\n" +
	"\x15WithdrawFundsResponse\"7\n" +
	"\x14CloseCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"\x17\n" +
	"\x15CloseCampaignResponse\">\n" +
	"\x1bWithdrawUnsoldTokensRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"\x1e\n" +
	"\x1cWithdrawUnsoldTokensResponse\"8\n" +
	"\x15DeleteCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"\x18\n" +
	"\x16DeleteCampaignResponse\"x\n" +
	"\x1bUpdateCampaignStatusRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .campaigns.public.CampaignStatusR\x06status\"\x1e\n" +
	"\x1cUpdateCampaignStatusResponse\"J\n" +
	"'CloseCampaignIfSoftCapNotReachedRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x04R\n" +
	"campaignId\"*\n" +
	"(CloseCampaignIfSoftCapNotReachedResponse*\xc3\x02\n" +
	"\x0eCampaignStatus\x12\x1d\n" +
	"\x19CAMPAIGN_STATUS_UNDEFINED\x10\x00\x12(\n" +
	"$CAMPAIGN_STATUS_TOKENS_NOT_DEPOSITED\x10\x01\x12%\n" +
	"!CAMPAIGN_STATUS_WAITING_FOR_START\x10\x02\x12 \n" +
	"\x1cCAMPAIGN_STATUS_SALE_STARTED\x10\x03\x12)\n" +
	"%CAMPAIGN_STATUS_SALE_ENDED_SUCCESSFUL\x10\x04\x12%\n" +
	"!CAMPAIGN_STATUS_SALE_ENDED_FAILED\x10\x05\x12(\n" +
	"$CAMPAIGN_STATUS_SALE_CLOSED_BY_OWNER\x10\x06\x12#\n" +
	"\x1fCAMPAIGN_STATUS_FUNDS_WITHDRAWN\x10\a2\xe9\t\n" +
	"\tCampaigns\x12c\n" +
	"\x0eCreateCampaign\x12'.campaigns.public.CreateCampaignRequest\x1a(.campaigns.public.CreateCampaignResponse\x12i\n" +
	"\x10GetCampaignsList\x12).campaigns.public.GetCampaignsListRequest\x1a*.campaigns.public.GetCampaignsListResponse\x12r\n" +
	"\x13DepositTokensToSale\x12,.campaigns.public.DepositTokensToSaleRequest\x1a-.campaigns.public.DepositTokensToSaleResponse\x12N\n" +
	"\aJoinIdo\x12 .campaigns.public.JoinIdoRequest\x1a!.campaigns.public.JoinIdoResponse\x12H\n" +
	"\x05Claim\x12\x1e.campaigns.public.ClaimRequest\x1a\x1f.campaigns.public.ClaimResponse\x12K\n" +
	"\x06Refund\x12\x1f.campaigns.public.RefundRequest\x1a .campaigns.public.RefundResponse\x12`\n" +
	"\rWithdrawFunds\x12&.campaigns.public.WithdrawFundsRequest\x1a'.campaigns.public.WithdrawFundsResponse\x12`\n" +
	"\rCloseCampaign\x12&.campaigns.public.CloseCampaignRequest\x1a'.campaigns.public.CloseCampaignResponse\x12u\n" +
	"\x14WithdrawUnsoldTokens\x12-.campaigns.public.WithdrawUnsoldTokensRequest\x1a..campaigns.public.WithdrawUnsoldTokensResponse\x12c\n" +
	"\x0eDeleteCampaign\x12'.campaigns.public.DeleteCampaignRequest\x1a(.campaigns.public.DeleteCampaignResponse\x12u\n" +
	"\x14UpdateCampaignStatus\x12-.campaigns.public.UpdateCampaignStatusRequest\x1a..campaigns.public.UpdateCampaignStatusResponse\x12\x99\x01\n" +
	" CloseCampaignIfSoftCapNotReached\x129.campaigns.public.CloseCampaignIfSoftCapNotReachedRequest\x1a:.campaigns.public.CloseCampaignIfSoftCapNotReachedResponseB\x04Z\x02./b\x06proto3"

var (
	file_campaigns_public_proto_rawDescOnce sync.Once
	file_campaigns_public_proto_rawDescData []byte
)

func file_campaigns_public_proto_rawDescGZIP() []byte {
	file_campaigns_public_proto_rawDescOnce.Do(func() {
		file_campaigns_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campaigns_public_proto_rawDesc), len(file_campaigns_public_proto_rawDesc)))
	})
	return file_campaigns_public_proto_rawDescData
}

var file_campaigns_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_campaigns_public_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_campaigns_public_proto_goTypes = []any{
	(CampaignStatus)(0),                              // 0: campaigns.public.CampaignStatus
	(*CreateCampaignRequest)(nil),                    // 1: campaigns.public.CreateCampaignRequest
	(*CreateCampaignResponse)(nil),                   // 2: campaigns.public.CreateCampaignResponse
	(*GetCampaignsListRequest)(nil),                  // 3: campaigns.public.GetCampaignsListRequest
	(*GetCampaignsListResponse)(nil),                 // 4: campaigns.public.GetCampaignsListResponse
	(*Pagination)(nil),                               // 5: campaigns.public.Pagination
	(*Campaign)(nil),                                 // 6: campaigns.public.Campaign
	(*DepositTokensToSaleRequest)(nil),               // 7: campaigns.public.DepositTokensToSaleRequest
	(*DepositTokensToSaleResponse)(nil),              // 8: campaigns.public.DepositTokensToSaleResponse
	(*JoinIdoRequest)(nil),                           // 9: campaigns.public.JoinIdoRequest
	(*JoinIdoResponse)(nil),                          // 10: campaigns.public.JoinIdoResponse
	(*ClaimRequest)(nil),                             // 11: campaigns.public.ClaimRequest
	(*ClaimResponse)(nil),                            // 12: campaigns.public.ClaimResponse
	(*RefundRequest)(nil),                            // 13: campaigns.public.RefundRequest
	(*RefundResponse)(nil),                           // 14: campaigns.public.RefundResponse
	(*WithdrawFundsRequest)(nil),                     // 15: campaigns.public.WithdrawFundsRequest
	(*WithdrawFundsResponse)(nil),                    // 16: campaigns.public.WithdrawFundsResponse
	(*CloseCampaignRequest)(nil),                     // 17: campaigns.public.CloseCampaignRequest
	(*CloseCampaignResponse)(nil),                    // 18: campaigns.public.CloseCampaignResponse
	(*WithdrawUnsoldTokensRequest)(nil),              // 19: campaigns.public.WithdrawUnsoldTokensRequest
	(*WithdrawUnsoldTokensResponse)(nil),             // 20: campaigns.public.WithdrawUnsoldTokensResponse
	(*DeleteCampaignRequest)(nil),                    // 21: campaigns.public.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil),                   // 22: campaigns.public.DeleteCampaignResponse
	(*UpdateCampaignStatusRequest)(nil),              // 23: campaigns.public.UpdateCampaignStatusRequest
	(*UpdateCampaignStatusResponse)(nil),             // 24: campaigns.public.UpdateCampaignStatusResponse
	(*CloseCampaignIfSoftCapNotReachedRequest)(nil),  // 25: campaigns.public.CloseCampaignIfSoftCapNotReachedRequest
	(*CloseCampaignIfSoftCapNotReachedResponse)(nil), // 26: campaigns.public.CloseCampaignIfSoftCapNotReachedResponse
}
var file_campaigns_public_proto_depIdxs = []int32{
	0,  // 0: campaigns.public.GetCampaignsListRequest.campaign_status:type_name -> campaigns.public.CampaignStatus
	6,  // 1: campaigns.public.GetCampaignsListResponse.campaigns:type_name -> campaigns.public.Campaign
	5,  // 2: campaigns.public.GetCampaignsListResponse.pagination:type_name -> campaigns.public.Pagination
	0,  // 3: campaigns.public.Campaign.campaign_status:type_name -> campaigns.public.CampaignStatus
	0,  // 4: campaigns.public.UpdateCampaignStatusRequest.status:type_name -> campaigns.public.CampaignStatus
	1,  // 5: campaigns.public.Campaigns.CreateCampaign:input_type -> campaigns.public.CreateCampaignRequest
	3,  // 6: campaigns.public.Campaigns.GetCampaignsList:input_type -> campaigns.public.GetCampaignsListRequest
	7,  // 7: campaigns.public.Campaigns.DepositTokensToSale:input_type -> campaigns.public.DepositTokensToSaleRequest
	9,  // 8: campaigns.public.Campaigns.JoinIdo:input_type -> campaigns.public.JoinIdoRequest
	11, // 9: campaigns.public.Campaigns.Claim:input_type -> campaigns.public.ClaimRequest
	13, // 10: campaigns.public.Campaigns.Refund:input_type -> campaigns.public.RefundRequest
	15, // 11: campaigns.public.Campaigns.WithdrawFunds:input_type -> campaigns.public.WithdrawFundsRequest
	17, // 12: campaigns.public.Campaigns.CloseCampaign:input_type -> campaigns.public.CloseCampaignRequest
	19, // 13: campaigns.public.Campaigns.WithdrawUnsoldTokens:input_type -> campaigns.public.WithdrawUnsoldTokensRequest
	21, // 14: campaigns.public.Campaigns.DeleteCampaign:input_type -> campaigns.public.DeleteCampaignRequest
	23, // 15: campaigns.public.Campaigns.UpdateCampaignStatus:input_type -> campaigns.public.UpdateCampaignStatusRequest
	25, // 16: campaigns.public.Campaigns.CloseCampaignIfSoftCapNotReached:input_type -> campaigns.public.CloseCampaignIfSoftCapNotReachedRequest
	2,  // 17: campaigns.public.Campaigns.CreateCampaign:output_type -> campaigns.public.CreateCampaignResponse
	4,  // 18: campaigns.public.Campaigns.GetCampaignsList:output_type -> campaigns.public.GetCampaignsListResponse
	8,  // 19: campaigns.public.Campaigns.DepositTokensToSale:output_type -> campaigns.public.DepositTokensToSaleResponse
	10, // 20: campaigns.public.Campaigns.JoinIdo:output_type -> campaigns.public.JoinIdoResponse
	12, // 21: campaigns.public.Campaigns.Claim:output_type -> campaigns.public.ClaimResponse
	14, // 22: campaigns.public.Campaigns.Refund:output_type -> campaigns.public.RefundResponse
	16, // 23: campaigns.public.Campaigns.WithdrawFunds:output_type -> campaigns.public.WithdrawFundsResponse
	18, // 24: campaigns.public.Campaigns.CloseCampaign:output_type -> campaigns.public.CloseCampaignResponse
	20, // 25: campaigns.public.Campaigns.WithdrawUnsoldTokens:output_type -> campaigns.public.WithdrawUnsoldTokensResponse
	22, // 26: campaigns.public.Campaigns.DeleteCampaign:output_type -> campaigns.public.DeleteCampaignResponse
	24, // 27: campaigns.public.Campaigns.UpdateCampaignStatus:output_type -> campaigns.public.UpdateCampaignStatusResponse
	26, // 28: campaigns.public.Campaigns.CloseCampaignIfSoftCapNotReached:output_type -> campaigns.public.CloseCampaignIfSoftCapNotReachedResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_campaigns_public_proto_init() }
func file_campaigns_public_proto_init() {
	if File_campaigns_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campaigns_public_proto_rawDesc), len(file_campaigns_public_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campaigns_public_proto_goTypes,
		DependencyIndexes: file_campaigns_public_proto_depIdxs,
		EnumInfos:         file_campaigns_public_proto_enumTypes,
		MessageInfos:      file_campaigns_public_proto_msgTypes,
	}.Build()
	File_campaigns_public_proto = out.File
	file_campaigns_public_proto_goTypes = nil
	file_campaigns_public_proto_depIdxs = nil
}
